# Following Along Tutorial

### Using Classes to now set up the NN

In [2]:
# Importing Numpy 

import numpy as np

In [4]:
# Setting random seed 

np.random.seed(0)

In [1]:
# Setting our inputs. 

X = [[1, 2, 3, 4],
     [2, 4, 1, 0],
     [0, -2, 1, -2]]

In [11]:
# Setting up classes for the NN.

class Layer_dense:
    
    def __init__(self, n_inputs,n_neurons):
        
        # intializing the weights. 
        self.weights = 0.1 * np.random.randn(n_inputs,n_neurons) 
        
        # Initialize the biases.
        self.biases = np.zeros((1,n_neurons))
    
    def forward(self,inputs):
        
        # Just combine the inputs with weights and biases.
        self.output = np.dot(inputs, self.weights) + self.biases

In [16]:
# Setting up the layers with our classes. 

layer1 = Layer_dense(4,5)
layer2 = Layer_dense(5,2)

# Now we do a forward pass. 

layer1.forward(X)

# printing out the output of the forward pass. 

print(layer1.output)

# Pass the output of layer one as input to layer 2 

layer2.forward(layer1.output)

# Print out the output.

print(layer2.output)

[[-0.2512756   0.05955416  0.34991886  0.88530914 -0.25585366]
 [-0.62960089 -0.02588446  0.00335235  0.19638068 -0.00567848]
 [ 0.49641904  0.03999113  0.15040863 -0.55448862 -0.06636312]]
[[-0.00351752  0.04041727]
 [ 0.06428252  0.02525265]
 [-0.07719795 -0.02559343]]
